const products = [
  {
    _id: "b1",
    name: "Beauty & The Beast",
    image: "/ProductsImg/Bracelets/beautybeast1.png",
    description:
      "The elegant silver bracelet with a touch of stone and silver tag",
    category: "bracelets",
    price: 39.5,
    rating: 4.5,
    numReviews: 6,
  },
  {
    _id: "b2",
    name: "Cinderella Bracelets",
    image: "/ProductsImg/Bracelets/cinderella1.png",
    description:
      "The elegant silver bracelet with a touch of stone and silver tag",
    category: "bracelets",
    price: 49.5,
    rating: 5,
    numReviews: 3,
  },
  {
    _id: "e1",
    name: "Fantasia Earings",
    image: "/ProductsImg/Earings/fantasia1.png",
    description: "The elegant silver earings with a touch of stone",
    category: "earingss",
    price: 28.9,
    rating: 4.8,
    numReviews: 5,
  },
  {
    _id: "e2",
    name: "Radiance Of Joy Earings",
    image: "/ProductsImg/Earings/radianceofjoy1.png",
    description: "The elegant silver earings with a touch of stone",
    category: "earings",
    price: 27.8,
    rating: 4.7,
    numReviews: 7,
  },
  {
    _id: "n1",
    name: "Sunflower Necklace",
    image: "/ProductsImg/Necklaces/sunflower1.png",
    description: "The elegant silver necklece with a touch of stone",
    category: "necklaces",
    price: 129.7,
    rating: 4.8,
    numReviews: 6,
  },
  {
    _id: "n2",
    name: "Embrace Necklace",
    image: "/ProductsImg/Necklaces/embrace1.png",
    description: "The elegant silver necklace with a touch of stone",
    category: "necklaces",
    price: 37.8,
    rating: 5,
    numReviews: 3,
  },
  {
    _id: "r1",
    name: "Princess Ring",
    image: "/ProductsImg/Rings/princess1.png",
    description: "The elegant silver ring with a touch of stone",
    category: "rings",
    price: 32.5,
    rating: 4.9,
    numReviews: 7,
  },
  {
    _id: "r2",
    name: "Berry Ring",
    image: "/ProductsImg/Rings/berry1.png",
    description: "The elegant silver ring with a touch of stone",
    category: "rings",
    price: 33.5,
    rating: 4.9,
    numReviews: 9,
  },
];

export default products;
